# See the dedicated "version" documentation section.
version: "2"
linters:
  default: all
  disable:
    - unparam
    - depguard
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - forbidigo
    - gocritic
    - gocyclo
    - cyclop
    - funlen
    - wsl
  enable:
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      # Source-based rules
      - linters:
          - structtag
        source: "`(cmd|arg)`"
      - linters:
          - lll
        source: "^//go:generate "
      - linters: # Disable global var warnings for idents prefixed "[dD]efault[…]".
          - gochecknoglobals
          - mnd
          - gomnd
        source: "^(var|const)?\\s+(([dD]efault|[gG]lobal)\\w*\\s*(=|[\\w\\.]+)|\\w+\\s*=\\s*sync\\.Once)"
      - linters: # Magic numbers in caller frame skip and file permissions
          - mnd
          - gomnd
        source: "runtime\\.Callers\\(4,"
      - linters: # Standard file permissions
          - mnd
          - gomnd
        source: "0o644"
        path: cli/log\.go
      - linters:
          - exhaustruct
          - mnd
          - gomnd
        source: "slog\\.Attr\\{\\}|Syntax\\{|kong\\.HelpOptions\\{"
      - linters:
          - ireturn
        source: "func (Make|Wrap)"
      - linters:
          - gochecknoglobals
        source: "map\\[string\\]func\\(\\*profile\\.Profile\\)"
        path: profile/pprof\.go
      - linters:
          - gosec
        source: "_ \"net/http/pprof\""
      # Test files
      - linters:
          - errcheck
          - dupl
          - gosec
        path: _test\.go
      # Text-based rules
      - linters:
          - goanalysis
          - staticcheck
          - unsafe
        text: "SA1012"
        path: log/log_test\.go
      # Parser core has many intentional patterns
      - linters:
          - mnd
          - gomnd
          - exhaustruct
          - noinlineerr
          - exhaustive
          - nestif
          - err113
          - nilnil
        path: lang/ast\.go
      # Complex functions that are difficult to simplify
      - linters:
          - gocognit
        path: (lang/marshal|log/pretty|cli/log)\.go
      - linters:
          - gocognit
          - nestif
        path: lang/format\.go
      # Inline error handling is idiomatic in certain contexts
      - linters:
          - noinlineerr
          - nilnil
        path: lang/(marshal|format|eval)\.go
      # Exhaustive struct initialization not required for constructors
      - linters:
          - exhaustruct
          - mnd
          - gomnd
          - nestif
          - gocognit
        path: (lang/(eval|cache|marshal|error|value)|cli/cmd/error)\.go
      # Magic numbers acceptable in error and marshal logic
      - linters:
          - exhaustive
        path: log/pretty\.go
      # CLI package rules
      - linters:
          - lll
        path: cli/
      - linters:
          - nilnil
          - ireturn
          - nilerr
        path: cli/resolver\.go
      - linters:
          - gochecknoglobals
          - mnd
          - gomnd
        path: (cli/path\.go|(doc|config)\.go|pkg/pkg\.go)
      # REPL package is a TUI application with framework-specific patterns
      - linters:
          - exhaustive
          - exhaustruct
          - gochecknoglobals
          - ireturn
          - mnd
          - gomnd
          - nestif
          - noinlineerr
        path: cli/cmd/repl/
      # Local go.mod replacements needed for development
      - linters:
          - gomoddirectives
        path: go\.mod
      - linters:
          - markdownlint
          - no-inline-html
        path: .github/instructions/
      - linters:
          - ireturn
        source: "func\\s+sourceFiles\\w*([^)]*)\\s+.+[(\\w,]*SourceFiles"
      - linters:
          - ireturn
        path: patcher\.go
      - linters:
          - contextcheck
        source: "ctx\\.(eval|build)"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/ardnew) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
      no-inline-comments: false
      no-prefix-comments: false
      custom-order: true
      no-lex-order: false
    gofmt:
      simplify: true
      rewrite-rules: []
    gofumpt:
      module-path: github.com/ardnew/aenv
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/ardnew/aenv
    golines:
      max-len: 80
      tab-len: 2
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true
  exclusions:
    warn-unused: true
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  # new-from-merge-base: main
  # new-from-rev: HEAD
  # new-from-patch: path/to/patch/file
  # whole-files: true
  fix: true

output:
  formats:
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true
      colors: true
    # json:
    #   path: stderr
    tab:
      path: stderr
      print-linter-name: true
      colors: true
    # html:
    #   path: stderr
  path-prefix: github.com/ardnew/aenv
  path-mode: abs
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

run:
  timeout: "0"
  relative-path-mode: gomod
  issues-exit-code: 100
  tests: false
  build-tags: ["pprof"]
  modules-download-mode: mod
  allow-parallel-runners: true
  allow-serial-runners: true
  # go: ''
  concurrency: 0

severity:
  default: "@linter"
  rules: []
