# See the dedicated "version" documentation section.
version: "2"
linters:
  default: all
  disable:
    - unparam
    - depguard
    - nonamedreturns
    - varnamelen
    - wrapcheck
    - forbidigo
    - gocritic
    - gocyclo
    - cyclop
    - funlen
    - wsl
  enable:
    - wsl_v5
  settings:
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: strict
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
    rules:
      # --- Source-based rules (project-wide semantic patterns) ---

      # Long go:generate directives
      - linters:
          - lll
        source: "^//go:generate "

      # Globals with Default/Global prefix or sync.Once initialization
      - linters:
          - gochecknoglobals
          - mnd
        source: "^(var|const)?\\s+(([dD]efault|[gG]lobal)\\w*\\s*(=|[\\w\\.]+)|\\w+\\s*=\\s*sync\\.Once)"

      # Magic number in runtime.Callers frame skip
      - linters:
          - mnd
        source: "runtime\\.Callers\\(4,"

      # Exhaustruct for partial struct literals of external types
      - linters:
          - exhaustruct
        source: "slog\\.Attr\\{\\}|kong\\.HelpOptions\\{"

      # Globals that are maps of profiling functions
      - linters:
          - gochecknoglobals
        source: "map\\[string\\]func\\(\\*profile\\.Profile\\)"
        path: profile/pprof\.go

      # Blanked pprof import is intentional
      - linters:
          - gosec
        source: "_ \"net/http/pprof\""

      # Functions returning the SourceFiles interface
      - linters:
          - ireturn
        source: "func\\s+\\w*[Ss]ourceFiles\\w*"

      # Domain-specific context methods, not context.Context
      - linters:
          - contextcheck
        source: "ctx\\.(eval|build)"

      # Singleton caches in env.go
      - linters:
          - gochecknoglobals
        source: "^\\s+(env|process)\\w+[^=]+$"
        path: lang/env\.go

      # Performance caches (sync.Pool, program cache) in eval.go
      - linters:
          - gochecknoglobals
        source: "(runtimeEnvPool|programCache)"
        path: lang/eval\.go

      # Standard file permission literals
      - linters:
          - mnd
        source: "0o644"
        path: cli/log\.go

      # --- Path-based rules (file/package scoped) ---

      # Parser core: intentional patterns throughout
      - linters:
          - exhaustruct
          - noinlineerr
          - exhaustive
          - err113
          - nilnil
        path: lang/ast\.go

      # Functions with high cognitive complexity
      - linters:
          - gocognit
        path: lang/(marshal|format|parse)\.go|log/pretty\.go|cli/log\.go

      # Deeply nested formatting logic
      - linters:
          - nestif
        path: lang/format\.go

      # Inline error handling is idiomatic in lang evaluator/serializer
      - linters:
          - noinlineerr
          - nilnil
        path: lang/(marshal|format|eval)\.go

      # Constructor and value-building code
      - linters:
          - exhaustruct
          - mnd
          - nestif
          - gocognit
        path: (lang/(eval|marshal|error|value|parse)|cli/cmd/error)\.go

      # Non-exhaustive switch on slog.Kind
      - linters:
          - exhaustive
        path: log/pretty\.go

      # CLI: long lines from Kong struct tags
      - linters:
          - lll
        path: cli/

      # Resolver returns nil values and interfaces by design
      - linters:
          - nilnil
          - ireturn
          - nilerr
        path: cli/resolver\.go

      # Globals and magic numbers in package metadata and config
      - linters:
          - gochecknoglobals
          - mnd
        path: (cli/path\.go|(doc|config)\.go|pkg/pkg\.go)

      # REPL: TUI application with framework-specific patterns
      - linters:
          - exhaustive
          - exhaustruct
          - gochecknoglobals
          - ireturn
          - mnd
          - nestif
          - noinlineerr
        path: cli/cmd/repl/

      # Local go.mod replacements needed for development
      - linters:
          - gomoddirectives
        path: go\.mod

      # Patcher returns ast.Node interface
      - linters:
          - ireturn
        path: patcher\.go

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard # Standard section: captures all standard packages.
        - default # Default section: contains all imports that could not be matched to another section type.
        - prefix(github.com/ardnew) # Custom section: groups all imports with the specified Prefix.
        - blank # Blank section: contains all blank imports. This section is not present unless explicitly enabled.
        - dot # Dot section: contains all dot imports. This section is not present unless explicitly enabled.
        - alias # Alias section: contains all alias imports. This section is not present unless explicitly enabled.
        - localmodule # Local module section: contains all local packages. This section is not present unless explicitly enabled.
      no-inline-comments: false
      no-prefix-comments: false
      custom-order: true
      no-lex-order: false
    gofmt:
      simplify: true
      rewrite-rules: []
    gofumpt:
      module-path: github.com/ardnew/aenv
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/ardnew/aenv
    golines:
      max-len: 80
      tab-len: 2
      shorten-comments: true
      reformat-tags: true
      chain-split-dots: true
  exclusions:
    warn-unused: true
    generated: strict

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: false
  # new-from-merge-base: main
  # new-from-rev: HEAD
  # new-from-patch: path/to/patch/file
  # whole-files: true
  fix: true

output:
  formats:
    text:
      path: stderr
      print-linter-name: true
      print-issued-lines: true
      colors: true
    # json:
    #   path: stderr
    tab:
      path: stderr
      print-linter-name: true
      colors: true
    # html:
    #   path: stderr
  path-prefix: github.com/ardnew/aenv
  path-mode: abs
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

run:
  timeout: "0"
  relative-path-mode: gomod
  issues-exit-code: 100
  tests: false
  build-tags: ["pprof"]
  modules-download-mode: mod
  allow-parallel-runners: true
  allow-serial-runners: true
  # go: ''
  concurrency: 0

severity:
  default: "@linter"
  rules: []
