// Code generated by "stringer --linecomment --type Level,Format --output config_string.go"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelTrace - -8]
	_ = x[LevelDebug - -4]
	_ = x[LevelInfo-0]
	_ = x[LevelWarn-4]
	_ = x[LevelError-8]
}

const (
	_Level_name_0 = "trace"
	_Level_name_1 = "debug"
	_Level_name_2 = "info"
	_Level_name_3 = "warn"
	_Level_name_4 = "error"
)

func (i Level) String() string {
	switch {
	case i == -8:
		return _Level_name_0
	case i == -4:
		return _Level_name_1
	case i == 0:
		return _Level_name_2
	case i == 4:
		return _Level_name_3
	case i == 8:
		return _Level_name_4
	default:
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatText-0]
	_ = x[FormatJSON-1]
}

const _Format_name = "textjson"

var _Format_index = [...]uint8{0, 4, 8}

func (i Format) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Format_index)-1 {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[idx]:_Format_index[idx+1]]
}
