// Code generated by "stringer -linecomment -type=Format"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormatText-1]
	_ = x[FormatJSON-2]
}

const _Format_name = "textjson"

var _Format_index = [...]uint8{0, 4, 8}

func (i Format) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Format_index)-1 {
		return "Format(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Format_name[_Format_index[idx]:_Format_index[idx+1]]
}
