// Code generated by "stringer -linecomment -type=Level"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelError-1]
	_ = x[LevelWarn-2]
	_ = x[LevelInfo-3]
	_ = x[LevelDebug-4]
	_ = x[LevelTrace-5]
}

const _Level_name = "errorwarninfodebugtrace"

var _Level_index = [...]uint8{0, 5, 9, 13, 18, 23}

func (i Level) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_Level_index)-1 {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[idx]:_Level_index[idx+1]]
}
