// Code generated by gogll. DO NOT EDIT.

package slot

import (
	"bytes"
	"fmt"

	"github.com/ardnew/aenv/lang/parser/symbols"
)

type Label int

const (
	Literal0R0 Label = iota
	Literal0R1
	Literal1R0
	Literal1R1
	Literal2R0
	Literal2R1
	Literal3R0
	Literal3R1
	Manifest0R0
	Manifest0R1
	Namespace0R0
	Namespace0R1
	Namespace0R2
	Namespace0R3
	Namespace0R4
	Namespaces0R0
	Namespaces0R1
	Namespaces0R2
	Namespaces1R0
	Namespaces1R1
	Namespaces1R2
	Namespaces1R3
	Namespaces2R0
	Parameters0R0
	Parameters0R1
	Parameters0R2
	Parameters1R0
	Tuple0R0
	Tuple0R1
	Tuple0R2
	Tuple0R3
	Value0R0
	Value0R1
	Value1R0
	Value1R1
	Value2R0
	Value2R1
	Value3R0
	Value3R1
	Values0R0
	Values0R1
	Values1R0
	Values1R1
	Values1R2
	Values1R3
	Values2R0
)

type Slot struct {
	NT      symbols.NT
	Alt     int
	Pos     int
	Symbols symbols.Symbols
	Label   Label
}

type Index struct {
	NT  symbols.NT
	Alt int
	Pos int
}

func GetAlternates(nt symbols.NT) []Label {
	alts, exist := alternates[nt]
	if !exist {
		panic(fmt.Sprintf("Invalid NT %s", nt))
	}
	return alts
}

func GetLabel(nt symbols.NT, alt, pos int) Label {
	l, exist := slotIndex[Index{nt, alt, pos}]
	if exist {
		return l
	}
	panic(fmt.Sprintf("Error: no slot label for NT=%s, alt=%d, pos=%d", nt, alt, pos))
}

func (l Label) EoR() bool {
	return l.Slot().EoR()
}

func (l Label) Head() symbols.NT {
	return l.Slot().NT
}

func (l Label) Index() Index {
	s := l.Slot()
	return Index{s.NT, s.Alt, s.Pos}
}

func (l Label) Alternate() int {
	return l.Slot().Alt
}

func (l Label) Pos() int {
	return l.Slot().Pos
}

func (l Label) Slot() *Slot {
	s, exist := slots[l]
	if !exist {
		panic(fmt.Sprintf("Invalid slot label %d", l))
	}
	return s
}

func (l Label) String() string {
	return l.Slot().String()
}

func (l Label) Symbols() symbols.Symbols {
	return l.Slot().Symbols
}

func (s *Slot) EoR() bool {
	return s.Pos >= len(s.Symbols)
}

func (s *Slot) String() string {
	buf := new(bytes.Buffer)
	fmt.Fprintf(buf, "%s : ", s.NT)
	for i, sym := range s.Symbols {
		if i == s.Pos {
			fmt.Fprintf(buf, "∙")
		}
		fmt.Fprintf(buf, "%s ", sym)
	}
	if s.Pos >= len(s.Symbols) {
		fmt.Fprintf(buf, "∙")
	}
	return buf.String()
}

var slots = map[Label]*Slot{
	Literal0R0: {
		symbols.NT_Literal, 0, 0,
		symbols.Symbols{
			symbols.T_1,
		},
		Literal0R0,
	},
	Literal0R1: {
		symbols.NT_Literal, 0, 1,
		symbols.Symbols{
			symbols.T_1,
		},
		Literal0R1,
	},
	Literal1R0: {
		symbols.NT_Literal, 1, 0,
		symbols.Symbols{
			symbols.T_6,
		},
		Literal1R0,
	},
	Literal1R1: {
		symbols.NT_Literal, 1, 1,
		symbols.Symbols{
			symbols.T_6,
		},
		Literal1R1,
	},
	Literal2R0: {
		symbols.NT_Literal, 2, 0,
		symbols.Symbols{
			symbols.T_9,
		},
		Literal2R0,
	},
	Literal2R1: {
		symbols.NT_Literal, 2, 1,
		symbols.Symbols{
			symbols.T_9,
		},
		Literal2R1,
	},
	Literal3R0: {
		symbols.NT_Literal, 3, 0,
		symbols.Symbols{
			symbols.T_3,
		},
		Literal3R0,
	},
	Literal3R1: {
		symbols.NT_Literal, 3, 1,
		symbols.Symbols{
			symbols.T_3,
		},
		Literal3R1,
	},
	Manifest0R0: {
		symbols.NT_Manifest, 0, 0,
		symbols.Symbols{
			symbols.NT_Namespaces,
		},
		Manifest0R0,
	},
	Manifest0R1: {
		symbols.NT_Manifest, 0, 1,
		symbols.Symbols{
			symbols.NT_Namespaces,
		},
		Manifest0R1,
	},
	Namespace0R0: {
		symbols.NT_Namespace, 0, 0,
		symbols.Symbols{
			symbols.T_4,
			symbols.NT_Parameters,
			symbols.T_7,
			symbols.NT_Value,
		},
		Namespace0R0,
	},
	Namespace0R1: {
		symbols.NT_Namespace, 0, 1,
		symbols.Symbols{
			symbols.T_4,
			symbols.NT_Parameters,
			symbols.T_7,
			symbols.NT_Value,
		},
		Namespace0R1,
	},
	Namespace0R2: {
		symbols.NT_Namespace, 0, 2,
		symbols.Symbols{
			symbols.T_4,
			symbols.NT_Parameters,
			symbols.T_7,
			symbols.NT_Value,
		},
		Namespace0R2,
	},
	Namespace0R3: {
		symbols.NT_Namespace, 0, 3,
		symbols.Symbols{
			symbols.T_4,
			symbols.NT_Parameters,
			symbols.T_7,
			symbols.NT_Value,
		},
		Namespace0R3,
	},
	Namespace0R4: {
		symbols.NT_Namespace, 0, 4,
		symbols.Symbols{
			symbols.T_4,
			symbols.NT_Parameters,
			symbols.T_7,
			symbols.NT_Value,
		},
		Namespace0R4,
	},
	Namespaces0R0: {
		symbols.NT_Namespaces, 0, 0,
		symbols.Symbols{
			symbols.NT_Namespace,
			symbols.NT_Namespaces,
		},
		Namespaces0R0,
	},
	Namespaces0R1: {
		symbols.NT_Namespaces, 0, 1,
		symbols.Symbols{
			symbols.NT_Namespace,
			symbols.NT_Namespaces,
		},
		Namespaces0R1,
	},
	Namespaces0R2: {
		symbols.NT_Namespaces, 0, 2,
		symbols.Symbols{
			symbols.NT_Namespace,
			symbols.NT_Namespaces,
		},
		Namespaces0R2,
	},
	Namespaces1R0: {
		symbols.NT_Namespaces, 1, 0,
		symbols.Symbols{
			symbols.NT_Namespace,
			symbols.T_8,
			symbols.NT_Namespaces,
		},
		Namespaces1R0,
	},
	Namespaces1R1: {
		symbols.NT_Namespaces, 1, 1,
		symbols.Symbols{
			symbols.NT_Namespace,
			symbols.T_8,
			symbols.NT_Namespaces,
		},
		Namespaces1R1,
	},
	Namespaces1R2: {
		symbols.NT_Namespaces, 1, 2,
		symbols.Symbols{
			symbols.NT_Namespace,
			symbols.T_8,
			symbols.NT_Namespaces,
		},
		Namespaces1R2,
	},
	Namespaces1R3: {
		symbols.NT_Namespaces, 1, 3,
		symbols.Symbols{
			symbols.NT_Namespace,
			symbols.T_8,
			symbols.NT_Namespaces,
		},
		Namespaces1R3,
	},
	Namespaces2R0: {
		symbols.NT_Namespaces, 2, 0,
		symbols.Symbols{},
		Namespaces2R0,
	},
	Parameters0R0: {
		symbols.NT_Parameters, 0, 0,
		symbols.Symbols{
			symbols.T_4,
			symbols.NT_Parameters,
		},
		Parameters0R0,
	},
	Parameters0R1: {
		symbols.NT_Parameters, 0, 1,
		symbols.Symbols{
			symbols.T_4,
			symbols.NT_Parameters,
		},
		Parameters0R1,
	},
	Parameters0R2: {
		symbols.NT_Parameters, 0, 2,
		symbols.Symbols{
			symbols.T_4,
			symbols.NT_Parameters,
		},
		Parameters0R2,
	},
	Parameters1R0: {
		symbols.NT_Parameters, 1, 0,
		symbols.Symbols{},
		Parameters1R0,
	},
	Tuple0R0: {
		symbols.NT_Tuple, 0, 0,
		symbols.Symbols{
			symbols.T_10,
			symbols.NT_Values,
			symbols.T_11,
		},
		Tuple0R0,
	},
	Tuple0R1: {
		symbols.NT_Tuple, 0, 1,
		symbols.Symbols{
			symbols.T_10,
			symbols.NT_Values,
			symbols.T_11,
		},
		Tuple0R1,
	},
	Tuple0R2: {
		symbols.NT_Tuple, 0, 2,
		symbols.Symbols{
			symbols.T_10,
			symbols.NT_Values,
			symbols.T_11,
		},
		Tuple0R2,
	},
	Tuple0R3: {
		symbols.NT_Tuple, 0, 3,
		symbols.Symbols{
			symbols.T_10,
			symbols.NT_Values,
			symbols.T_11,
		},
		Tuple0R3,
	},
	Value0R0: {
		symbols.NT_Value, 0, 0,
		symbols.Symbols{
			symbols.NT_Literal,
		},
		Value0R0,
	},
	Value0R1: {
		symbols.NT_Value, 0, 1,
		symbols.Symbols{
			symbols.NT_Literal,
		},
		Value0R1,
	},
	Value1R0: {
		symbols.NT_Value, 1, 0,
		symbols.Symbols{
			symbols.NT_Tuple,
		},
		Value1R0,
	},
	Value1R1: {
		symbols.NT_Value, 1, 1,
		symbols.Symbols{
			symbols.NT_Tuple,
		},
		Value1R1,
	},
	Value2R0: {
		symbols.NT_Value, 2, 0,
		symbols.Symbols{
			symbols.NT_Namespace,
		},
		Value2R0,
	},
	Value2R1: {
		symbols.NT_Value, 2, 1,
		symbols.Symbols{
			symbols.NT_Namespace,
		},
		Value2R1,
	},
	Value3R0: {
		symbols.NT_Value, 3, 0,
		symbols.Symbols{
			symbols.T_4,
		},
		Value3R0,
	},
	Value3R1: {
		symbols.NT_Value, 3, 1,
		symbols.Symbols{
			symbols.T_4,
		},
		Value3R1,
	},
	Values0R0: {
		symbols.NT_Values, 0, 0,
		symbols.Symbols{
			symbols.NT_Value,
		},
		Values0R0,
	},
	Values0R1: {
		symbols.NT_Values, 0, 1,
		symbols.Symbols{
			symbols.NT_Value,
		},
		Values0R1,
	},
	Values1R0: {
		symbols.NT_Values, 1, 0,
		symbols.Symbols{
			symbols.NT_Value,
			symbols.T_2,
			symbols.NT_Values,
		},
		Values1R0,
	},
	Values1R1: {
		symbols.NT_Values, 1, 1,
		symbols.Symbols{
			symbols.NT_Value,
			symbols.T_2,
			symbols.NT_Values,
		},
		Values1R1,
	},
	Values1R2: {
		symbols.NT_Values, 1, 2,
		symbols.Symbols{
			symbols.NT_Value,
			symbols.T_2,
			symbols.NT_Values,
		},
		Values1R2,
	},
	Values1R3: {
		symbols.NT_Values, 1, 3,
		symbols.Symbols{
			symbols.NT_Value,
			symbols.T_2,
			symbols.NT_Values,
		},
		Values1R3,
	},
	Values2R0: {
		symbols.NT_Values, 2, 0,
		symbols.Symbols{},
		Values2R0,
	},
}

var slotIndex = map[Index]Label{
	{symbols.NT_Literal, 0, 0}:    Literal0R0,
	{symbols.NT_Literal, 0, 1}:    Literal0R1,
	{symbols.NT_Literal, 1, 0}:    Literal1R0,
	{symbols.NT_Literal, 1, 1}:    Literal1R1,
	{symbols.NT_Literal, 2, 0}:    Literal2R0,
	{symbols.NT_Literal, 2, 1}:    Literal2R1,
	{symbols.NT_Literal, 3, 0}:    Literal3R0,
	{symbols.NT_Literal, 3, 1}:    Literal3R1,
	{symbols.NT_Manifest, 0, 0}:   Manifest0R0,
	{symbols.NT_Manifest, 0, 1}:   Manifest0R1,
	{symbols.NT_Namespace, 0, 0}:  Namespace0R0,
	{symbols.NT_Namespace, 0, 1}:  Namespace0R1,
	{symbols.NT_Namespace, 0, 2}:  Namespace0R2,
	{symbols.NT_Namespace, 0, 3}:  Namespace0R3,
	{symbols.NT_Namespace, 0, 4}:  Namespace0R4,
	{symbols.NT_Namespaces, 0, 0}: Namespaces0R0,
	{symbols.NT_Namespaces, 0, 1}: Namespaces0R1,
	{symbols.NT_Namespaces, 0, 2}: Namespaces0R2,
	{symbols.NT_Namespaces, 1, 0}: Namespaces1R0,
	{symbols.NT_Namespaces, 1, 1}: Namespaces1R1,
	{symbols.NT_Namespaces, 1, 2}: Namespaces1R2,
	{symbols.NT_Namespaces, 1, 3}: Namespaces1R3,
	{symbols.NT_Namespaces, 2, 0}: Namespaces2R0,
	{symbols.NT_Parameters, 0, 0}: Parameters0R0,
	{symbols.NT_Parameters, 0, 1}: Parameters0R1,
	{symbols.NT_Parameters, 0, 2}: Parameters0R2,
	{symbols.NT_Parameters, 1, 0}: Parameters1R0,
	{symbols.NT_Tuple, 0, 0}:      Tuple0R0,
	{symbols.NT_Tuple, 0, 1}:      Tuple0R1,
	{symbols.NT_Tuple, 0, 2}:      Tuple0R2,
	{symbols.NT_Tuple, 0, 3}:      Tuple0R3,
	{symbols.NT_Value, 0, 0}:      Value0R0,
	{symbols.NT_Value, 0, 1}:      Value0R1,
	{symbols.NT_Value, 1, 0}:      Value1R0,
	{symbols.NT_Value, 1, 1}:      Value1R1,
	{symbols.NT_Value, 2, 0}:      Value2R0,
	{symbols.NT_Value, 2, 1}:      Value2R1,
	{symbols.NT_Value, 3, 0}:      Value3R0,
	{symbols.NT_Value, 3, 1}:      Value3R1,
	{symbols.NT_Values, 0, 0}:     Values0R0,
	{symbols.NT_Values, 0, 1}:     Values0R1,
	{symbols.NT_Values, 1, 0}:     Values1R0,
	{symbols.NT_Values, 1, 1}:     Values1R1,
	{symbols.NT_Values, 1, 2}:     Values1R2,
	{symbols.NT_Values, 1, 3}:     Values1R3,
	{symbols.NT_Values, 2, 0}:     Values2R0,
}

var alternates = map[symbols.NT][]Label{
	symbols.NT_Manifest:   {Manifest0R0},
	symbols.NT_Namespaces: {Namespaces0R0, Namespaces1R0, Namespaces2R0},
	symbols.NT_Namespace:  {Namespace0R0},
	symbols.NT_Parameters: {Parameters0R0, Parameters1R0},
	symbols.NT_Value:      {Value0R0, Value1R0, Value2R0, Value3R0},
	symbols.NT_Values:     {Values0R0, Values1R0, Values2R0},
	symbols.NT_Literal:    {Literal0R0, Literal1R0, Literal2R0, Literal3R0},
	symbols.NT_Tuple:      {Tuple0R0},
}
