// Code generated by "stringer -type=editMode -linecomment"; DO NOT EDIT.

package cli

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[editNone-0]
	_ = x[editLine-1]
	_ = x[editArea-2]
}

const _editMode_name = "no-editorline-editormultiline-editor"

var _editMode_index = [...]uint8{0, 9, 20, 36}

func (i editMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_editMode_index)-1 {
		return "editMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _editMode_name[_editMode_index[idx]:_editMode_index[idx+1]]
}
