// Code generated by gogll. DO NOT EDIT.

package parser

import (
	"bytes"
	"fmt"
	"sort"
	"strings"

	"github.com/ardnew/aenv/lang/lexer"
	"github.com/ardnew/aenv/lang/parser/bsr"
	"github.com/ardnew/aenv/lang/parser/slot"
	"github.com/ardnew/aenv/lang/parser/symbols"
	"github.com/ardnew/aenv/lang/token"
)

type parser struct {
	cI int

	R *descriptors
	U *descriptors

	popped   map[poppedNode]bool
	crf      map[clusterNode][]*crfNode
	crfNodes map[crfNode]*crfNode

	lex         *lexer.Lexer
	parseErrors []*Error

	bsrSet *bsr.Set
}

func newParser(l *lexer.Lexer) *parser {
	return &parser{
		cI:     0,
		lex:    l,
		R:      &descriptors{},
		U:      &descriptors{},
		popped: make(map[poppedNode]bool),
		crf: map[clusterNode][]*crfNode{
			{symbols.NT_Manifest, 0}: {},
		},
		crfNodes:    map[crfNode]*crfNode{},
		bsrSet:      bsr.New(symbols.NT_Manifest, l),
		parseErrors: nil,
	}
}

// Parse returns the BSR set containing the parse forest.
// If the parse was successfull []*Error is nil
func Parse(l *lexer.Lexer) (*bsr.Set, []*Error) {
	return newParser(l).parse()
}

func (p *parser) parse() (*bsr.Set, []*Error) {
	var L slot.Label
	m, cU := len(p.lex.Tokens)-1, 0
	p.ntAdd(symbols.NT_Manifest, 0)
	// p.DumpDescriptors()
	for !p.R.empty() {
		L, cU, p.cI = p.R.remove()

		// fmt.Println()
		// fmt.Printf("L:%s, cI:%d, I[p.cI]:%s, cU:%d\n", L, p.cI, p.lex.Tokens[p.cI], cU)
		// p.DumpDescriptors()

		switch L {
		case slot.Literal0R0: // Literal : ∙boolean_literal

			p.bsrSet.Add(slot.Literal0R1, cU, p.cI, p.cI+1)
			p.cI++
			if p.follow(symbols.NT_Literal) {
				p.rtn(symbols.NT_Literal, cU, p.cI)
			} else {
				p.parseError(slot.Literal0R0, p.cI, followSets[symbols.NT_Literal])
			}
		case slot.Literal1R0: // Literal : ∙number_literal

			p.bsrSet.Add(slot.Literal1R1, cU, p.cI, p.cI+1)
			p.cI++
			if p.follow(symbols.NT_Literal) {
				p.rtn(symbols.NT_Literal, cU, p.cI)
			} else {
				p.parseError(slot.Literal1R0, p.cI, followSets[symbols.NT_Literal])
			}
		case slot.Literal2R0: // Literal : ∙string_literal

			p.bsrSet.Add(slot.Literal2R1, cU, p.cI, p.cI+1)
			p.cI++
			if p.follow(symbols.NT_Literal) {
				p.rtn(symbols.NT_Literal, cU, p.cI)
			} else {
				p.parseError(slot.Literal2R0, p.cI, followSets[symbols.NT_Literal])
			}
		case slot.Literal3R0: // Literal : ∙expr_literal

			p.bsrSet.Add(slot.Literal3R1, cU, p.cI, p.cI+1)
			p.cI++
			if p.follow(symbols.NT_Literal) {
				p.rtn(symbols.NT_Literal, cU, p.cI)
			} else {
				p.parseError(slot.Literal3R0, p.cI, followSets[symbols.NT_Literal])
			}
		case slot.Manifest0R0: // Manifest : ∙Namespaces

			p.call(slot.Manifest0R1, cU, p.cI)
		case slot.Manifest0R1: // Manifest : Namespaces ∙

			if p.follow(symbols.NT_Manifest) {
				p.rtn(symbols.NT_Manifest, cU, p.cI)
			} else {
				p.parseError(slot.Manifest0R0, p.cI, followSets[symbols.NT_Manifest])
			}
		case slot.Namespace0R0: // Namespace : ∙identifier Parameters op_define Value

			p.bsrSet.Add(slot.Namespace0R1, cU, p.cI, p.cI+1)
			p.cI++
			if !p.testSelect(slot.Namespace0R1) {
				p.parseError(slot.Namespace0R1, p.cI, first[slot.Namespace0R1])
				break
			}

			p.call(slot.Namespace0R2, cU, p.cI)
		case slot.Namespace0R2: // Namespace : identifier Parameters ∙op_define Value

			if !p.testSelect(slot.Namespace0R2) {
				p.parseError(slot.Namespace0R2, p.cI, first[slot.Namespace0R2])
				break
			}

			p.bsrSet.Add(slot.Namespace0R3, cU, p.cI, p.cI+1)
			p.cI++
			if !p.testSelect(slot.Namespace0R3) {
				p.parseError(slot.Namespace0R3, p.cI, first[slot.Namespace0R3])
				break
			}

			p.call(slot.Namespace0R4, cU, p.cI)
		case slot.Namespace0R4: // Namespace : identifier Parameters op_define Value ∙

			if p.follow(symbols.NT_Namespace) {
				p.rtn(symbols.NT_Namespace, cU, p.cI)
			} else {
				p.parseError(slot.Namespace0R0, p.cI, followSets[symbols.NT_Namespace])
			}
		case slot.Namespaces0R0: // Namespaces : ∙Namespace Namespaces

			p.call(slot.Namespaces0R1, cU, p.cI)
		case slot.Namespaces0R1: // Namespaces : Namespace ∙Namespaces

			if !p.testSelect(slot.Namespaces0R1) {
				p.parseError(slot.Namespaces0R1, p.cI, first[slot.Namespaces0R1])
				break
			}

			p.call(slot.Namespaces0R2, cU, p.cI)
		case slot.Namespaces0R2: // Namespaces : Namespace Namespaces ∙

			if p.follow(symbols.NT_Namespaces) {
				p.rtn(symbols.NT_Namespaces, cU, p.cI)
			} else {
				p.parseError(slot.Namespaces0R0, p.cI, followSets[symbols.NT_Namespaces])
			}
		case slot.Namespaces1R0: // Namespaces : ∙Namespace separator Namespaces

			p.call(slot.Namespaces1R1, cU, p.cI)
		case slot.Namespaces1R1: // Namespaces : Namespace ∙separator Namespaces

			if !p.testSelect(slot.Namespaces1R1) {
				p.parseError(slot.Namespaces1R1, p.cI, first[slot.Namespaces1R1])
				break
			}

			p.bsrSet.Add(slot.Namespaces1R2, cU, p.cI, p.cI+1)
			p.cI++
			if !p.testSelect(slot.Namespaces1R2) {
				p.parseError(slot.Namespaces1R2, p.cI, first[slot.Namespaces1R2])
				break
			}

			p.call(slot.Namespaces1R3, cU, p.cI)
		case slot.Namespaces1R3: // Namespaces : Namespace separator Namespaces ∙

			if p.follow(symbols.NT_Namespaces) {
				p.rtn(symbols.NT_Namespaces, cU, p.cI)
			} else {
				p.parseError(slot.Namespaces1R0, p.cI, followSets[symbols.NT_Namespaces])
			}
		case slot.Namespaces2R0: // Namespaces : ∙
			p.bsrSet.AddEmpty(slot.Namespaces2R0, p.cI)

			if p.follow(symbols.NT_Namespaces) {
				p.rtn(symbols.NT_Namespaces, cU, p.cI)
			} else {
				p.parseError(slot.Namespaces2R0, p.cI, followSets[symbols.NT_Namespaces])
			}
		case slot.Parameters0R0: // Parameters : ∙identifier Parameters

			p.bsrSet.Add(slot.Parameters0R1, cU, p.cI, p.cI+1)
			p.cI++
			if !p.testSelect(slot.Parameters0R1) {
				p.parseError(slot.Parameters0R1, p.cI, first[slot.Parameters0R1])
				break
			}

			p.call(slot.Parameters0R2, cU, p.cI)
		case slot.Parameters0R2: // Parameters : identifier Parameters ∙

			if p.follow(symbols.NT_Parameters) {
				p.rtn(symbols.NT_Parameters, cU, p.cI)
			} else {
				p.parseError(slot.Parameters0R0, p.cI, followSets[symbols.NT_Parameters])
			}
		case slot.Parameters1R0: // Parameters : ∙
			p.bsrSet.AddEmpty(slot.Parameters1R0, p.cI)

			if p.follow(symbols.NT_Parameters) {
				p.rtn(symbols.NT_Parameters, cU, p.cI)
			} else {
				p.parseError(slot.Parameters1R0, p.cI, followSets[symbols.NT_Parameters])
			}
		case slot.Tuple0R0: // Tuple : ∙{ Values }

			p.bsrSet.Add(slot.Tuple0R1, cU, p.cI, p.cI+1)
			p.cI++
			if !p.testSelect(slot.Tuple0R1) {
				p.parseError(slot.Tuple0R1, p.cI, first[slot.Tuple0R1])
				break
			}

			p.call(slot.Tuple0R2, cU, p.cI)
		case slot.Tuple0R2: // Tuple : { Values ∙}

			if !p.testSelect(slot.Tuple0R2) {
				p.parseError(slot.Tuple0R2, p.cI, first[slot.Tuple0R2])
				break
			}

			p.bsrSet.Add(slot.Tuple0R3, cU, p.cI, p.cI+1)
			p.cI++
			if p.follow(symbols.NT_Tuple) {
				p.rtn(symbols.NT_Tuple, cU, p.cI)
			} else {
				p.parseError(slot.Tuple0R0, p.cI, followSets[symbols.NT_Tuple])
			}
		case slot.Value0R0: // Value : ∙Literal

			p.call(slot.Value0R1, cU, p.cI)
		case slot.Value0R1: // Value : Literal ∙

			if p.follow(symbols.NT_Value) {
				p.rtn(symbols.NT_Value, cU, p.cI)
			} else {
				p.parseError(slot.Value0R0, p.cI, followSets[symbols.NT_Value])
			}
		case slot.Value1R0: // Value : ∙Tuple

			p.call(slot.Value1R1, cU, p.cI)
		case slot.Value1R1: // Value : Tuple ∙

			if p.follow(symbols.NT_Value) {
				p.rtn(symbols.NT_Value, cU, p.cI)
			} else {
				p.parseError(slot.Value1R0, p.cI, followSets[symbols.NT_Value])
			}
		case slot.Value2R0: // Value : ∙Namespace

			p.call(slot.Value2R1, cU, p.cI)
		case slot.Value2R1: // Value : Namespace ∙

			if p.follow(symbols.NT_Value) {
				p.rtn(symbols.NT_Value, cU, p.cI)
			} else {
				p.parseError(slot.Value2R0, p.cI, followSets[symbols.NT_Value])
			}
		case slot.Value3R0: // Value : ∙identifier

			p.bsrSet.Add(slot.Value3R1, cU, p.cI, p.cI+1)
			p.cI++
			if p.follow(symbols.NT_Value) {
				p.rtn(symbols.NT_Value, cU, p.cI)
			} else {
				p.parseError(slot.Value3R0, p.cI, followSets[symbols.NT_Value])
			}
		case slot.Values0R0: // Values : ∙Value

			p.call(slot.Values0R1, cU, p.cI)
		case slot.Values0R1: // Values : Value ∙

			if p.follow(symbols.NT_Values) {
				p.rtn(symbols.NT_Values, cU, p.cI)
			} else {
				p.parseError(slot.Values0R0, p.cI, followSets[symbols.NT_Values])
			}
		case slot.Values1R0: // Values : ∙Value delimiter Values

			p.call(slot.Values1R1, cU, p.cI)
		case slot.Values1R1: // Values : Value ∙delimiter Values

			if !p.testSelect(slot.Values1R1) {
				p.parseError(slot.Values1R1, p.cI, first[slot.Values1R1])
				break
			}

			p.bsrSet.Add(slot.Values1R2, cU, p.cI, p.cI+1)
			p.cI++
			if !p.testSelect(slot.Values1R2) {
				p.parseError(slot.Values1R2, p.cI, first[slot.Values1R2])
				break
			}

			p.call(slot.Values1R3, cU, p.cI)
		case slot.Values1R3: // Values : Value delimiter Values ∙

			if p.follow(symbols.NT_Values) {
				p.rtn(symbols.NT_Values, cU, p.cI)
			} else {
				p.parseError(slot.Values1R0, p.cI, followSets[symbols.NT_Values])
			}
		case slot.Values2R0: // Values : ∙
			p.bsrSet.AddEmpty(slot.Values2R0, p.cI)

			if p.follow(symbols.NT_Values) {
				p.rtn(symbols.NT_Values, cU, p.cI)
			} else {
				p.parseError(slot.Values2R0, p.cI, followSets[symbols.NT_Values])
			}

		default:
			panic("This must not happen")
		}
	}
	if !p.bsrSet.Contain(symbols.NT_Manifest, 0, m) {
		p.sortParseErrors()
		return nil, p.parseErrors
	}
	return p.bsrSet, nil
}

func (p *parser) ntAdd(nt symbols.NT, j int) {
	// fmt.Printf("p.ntAdd(%s, %d)\n", nt, j)
	failed := true
	expected := map[token.Type]string{}
	for _, l := range slot.GetAlternates(nt) {
		if p.testSelect(l) {
			p.dscAdd(l, j, j)
			failed = false
		} else {
			for k, v := range first[l] {
				expected[k] = v
			}
		}
	}
	if failed {
		for _, l := range slot.GetAlternates(nt) {
			p.parseError(l, j, expected)
		}
	}
}

/*** Call Return Forest ***/

type poppedNode struct {
	X    symbols.NT
	k, j int
}

type clusterNode struct {
	X symbols.NT
	k int
}

type crfNode struct {
	L slot.Label
	i int
}

/*
suppose that L is Y ::=αX ·β
if there is no CRF node labelled (L,i)

	create one let u be the CRF node labelled (L,i)

if there is no CRF node labelled (X, j) {

		create a CRF node v labelled (X, j)
		create an edge from v to u
		ntAdd(X, j)
	} else {

		let v be the CRF node labelled (X, j)
		if there is not an edge from v to u {
			create an edge from v to u
			for all ((X, j,h)∈P) {
				dscAdd(L, i, h);
				bsrAdd(L, i, j, h)
			}
		}
	}
*/
func (p *parser) call(L slot.Label, i, j int) {
	// fmt.Printf("p.call(%s,%d,%d)\n", L,i,j)
	u, exist := p.crfNodes[crfNode{L, i}]
	// fmt.Printf("  u exist=%t\n", exist)
	if !exist {
		u = &crfNode{L, i}
		p.crfNodes[*u] = u
	}
	X := L.Symbols()[L.Pos()-1].(symbols.NT)
	ndV := clusterNode{X, j}
	v, exist := p.crf[ndV]
	if !exist {
		// fmt.Println("  v !exist")
		p.crf[ndV] = []*crfNode{u}
		p.ntAdd(X, j)
	} else {
		// fmt.Println("  v exist")
		if !existEdge(v, u) {
			// fmt.Printf("  !existEdge(%v)\n", u)
			p.crf[ndV] = append(v, u)
			// fmt.Printf("|popped|=%d\n", len(popped))
			for pnd := range p.popped {
				if pnd.X == X && pnd.k == j {
					p.dscAdd(L, i, pnd.j)
					p.bsrSet.Add(L, i, j, pnd.j)
				}
			}
		}
	}
}

func existEdge(nds []*crfNode, nd *crfNode) bool {
	for _, nd1 := range nds {
		if nd1 == nd {
			return true
		}
	}
	return false
}

func (p *parser) rtn(X symbols.NT, k, j int) {
	// fmt.Printf("p.rtn(%s,%d,%d)\n", X,k,j)
	pn := poppedNode{X, k, j}
	if _, exist := p.popped[pn]; !exist {
		p.popped[pn] = true
		for _, nd := range p.crf[clusterNode{X, k}] {
			p.dscAdd(nd.L, nd.i, j)
			p.bsrSet.Add(nd.L, nd.i, k, j)
		}
	}
}

// func CRFString() string {
// 	buf := new(bytes.Buffer)
// 	buf.WriteString("CRF: {")
// 	for cn, nds := range crf{
// 		for _, nd := range nds {
// 			fmt.Fprintf(buf, "%s->%s, ", cn, nd)
// 		}
// 	}
// 	buf.WriteString("}")
// 	return buf.String()
// }

func (cn clusterNode) String() string {
	return fmt.Sprintf("(%s,%d)", cn.X, cn.k)
}

func (n crfNode) String() string {
	return fmt.Sprintf("(%s,%d)", n.L.String(), n.i)
}

// func PoppedString() string {
// 	buf := new(bytes.Buffer)
// 	buf.WriteString("Popped: {")
// 	for p, _ := range popped {
// 		fmt.Fprintf(buf, "(%s,%d,%d) ", p.X, p.k, p.j)
// 	}
// 	buf.WriteString("}")
// 	return buf.String()
// }

/*** descriptors ***/

type descriptors struct {
	set []*descriptor
}

func (ds *descriptors) contain(d *descriptor) bool {
	for _, d1 := range ds.set {
		if d1 == d {
			return true
		}
	}
	return false
}

func (ds *descriptors) empty() bool {
	return len(ds.set) == 0
}

func (ds *descriptors) String() string {
	buf := new(bytes.Buffer)
	buf.WriteString("{")
	for i, d := range ds.set {
		if i > 0 {
			buf.WriteString("; ")
		}
		fmt.Fprintf(buf, "%s", d)
	}
	buf.WriteString("}")
	return buf.String()
}

type descriptor struct {
	L slot.Label
	k int
	i int
}

func (d *descriptor) String() string {
	return fmt.Sprintf("%s,%d,%d", d.L, d.k, d.i)
}

func (p *parser) dscAdd(L slot.Label, k, i int) {
	// fmt.Printf("p.dscAdd(%s,%d,%d)\n", L, k, i)
	d := &descriptor{L, k, i}
	if !p.U.contain(d) {
		p.R.set = append(p.R.set, d)
		p.U.set = append(p.U.set, d)
	}
}

func (ds *descriptors) remove() (L slot.Label, k, i int) {
	d := ds.set[len(ds.set)-1]
	ds.set = ds.set[:len(ds.set)-1]
	// fmt.Printf("remove: %s,%d,%d\n", d.L, d.k, d.i)
	return d.L, d.k, d.i
}

func (p *parser) DumpDescriptors() {
	p.DumpR()
	p.DumpU()
}

func (p *parser) DumpR() {
	fmt.Println("R:")
	for _, d := range p.R.set {
		fmt.Printf(" %s\n", d)
	}
}

func (p *parser) DumpU() {
	fmt.Println("U:")
	for _, d := range p.U.set {
		fmt.Printf(" %s\n", d)
	}
}

/*** TestSelect ***/

func (p *parser) follow(nt symbols.NT) bool {
	_, exist := followSets[nt][p.lex.Tokens[p.cI].Type()]
	return exist
}

func (p *parser) testSelect(l slot.Label) bool {
	_, exist := first[l][p.lex.Tokens[p.cI].Type()]
	// fmt.Printf("testSelect(%s) = %t\n", l, exist)
	return exist
}

var first = []map[token.Type]string{
	// Literal : ∙boolean_literal
	{
		token.T_1: "boolean_literal",
	},
	// Literal : boolean_literal ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Literal : ∙number_literal
	{
		token.T_6: "number_literal",
	},
	// Literal : number_literal ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Literal : ∙string_literal
	{
		token.T_9: "string_literal",
	},
	// Literal : string_literal ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Literal : ∙expr_literal
	{
		token.T_3: "expr_literal",
	},
	// Literal : expr_literal ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Manifest : ∙Namespaces
	{
		token.T_4: "identifier",
		token.EOF: "$",
	},
	// Manifest : Namespaces ∙
	{
		token.EOF: "$",
	},
	// Namespace : ∙identifier Parameters op_define Value
	{
		token.T_4: "identifier",
	},
	// Namespace : identifier ∙Parameters op_define Value
	{
		token.T_4: "identifier",
		token.T_7: "op_define",
	},
	// Namespace : identifier Parameters ∙op_define Value
	{
		token.T_7: "op_define",
	},
	// Namespace : identifier Parameters op_define ∙Value
	{
		token.T_1:  "boolean_literal",
		token.T_3:  "expr_literal",
		token.T_4:  "identifier",
		token.T_6:  "number_literal",
		token.T_9:  "string_literal",
		token.T_10: "{",
	},
	// Namespace : identifier Parameters op_define Value ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Namespaces : ∙Namespace Namespaces
	{
		token.T_4: "identifier",
	},
	// Namespaces : Namespace ∙Namespaces
	{
		token.T_4: "identifier",
		token.EOF: "$",
	},
	// Namespaces : Namespace Namespaces ∙
	{
		token.EOF: "$",
	},
	// Namespaces : ∙Namespace separator Namespaces
	{
		token.T_4: "identifier",
	},
	// Namespaces : Namespace ∙separator Namespaces
	{
		token.T_8: "separator",
	},
	// Namespaces : Namespace separator ∙Namespaces
	{
		token.T_4: "identifier",
		token.EOF: "$",
	},
	// Namespaces : Namespace separator Namespaces ∙
	{
		token.EOF: "$",
	},
	// Namespaces : ∙
	{
		token.EOF: "$",
	},
	// Parameters : ∙identifier Parameters
	{
		token.T_4: "identifier",
	},
	// Parameters : identifier ∙Parameters
	{
		token.T_4: "identifier",
		token.T_7: "op_define",
	},
	// Parameters : identifier Parameters ∙
	{
		token.T_7: "op_define",
	},
	// Parameters : ∙
	{
		token.T_7: "op_define",
	},
	// Tuple : ∙{ Values }
	{
		token.T_10: "{",
	},
	// Tuple : { ∙Values }
	{
		token.T_1:  "boolean_literal",
		token.T_3:  "expr_literal",
		token.T_4:  "identifier",
		token.T_6:  "number_literal",
		token.T_9:  "string_literal",
		token.T_10: "{",
		token.T_11: "}",
	},
	// Tuple : { Values ∙}
	{
		token.T_11: "}",
	},
	// Tuple : { Values } ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Value : ∙Literal
	{
		token.T_1: "boolean_literal",
		token.T_3: "expr_literal",
		token.T_6: "number_literal",
		token.T_9: "string_literal",
	},
	// Value : Literal ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Value : ∙Tuple
	{
		token.T_10: "{",
	},
	// Value : Tuple ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Value : ∙Namespace
	{
		token.T_4: "identifier",
	},
	// Value : Namespace ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Value : ∙identifier
	{
		token.T_4: "identifier",
	},
	// Value : identifier ∙
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Values : ∙Value
	{
		token.T_1:  "boolean_literal",
		token.T_3:  "expr_literal",
		token.T_4:  "identifier",
		token.T_6:  "number_literal",
		token.T_9:  "string_literal",
		token.T_10: "{",
	},
	// Values : Value ∙
	{
		token.T_11: "}",
	},
	// Values : ∙Value delimiter Values
	{
		token.T_1:  "boolean_literal",
		token.T_3:  "expr_literal",
		token.T_4:  "identifier",
		token.T_6:  "number_literal",
		token.T_9:  "string_literal",
		token.T_10: "{",
	},
	// Values : Value ∙delimiter Values
	{
		token.T_2: "delimiter",
	},
	// Values : Value delimiter ∙Values
	{
		token.T_1:  "boolean_literal",
		token.T_3:  "expr_literal",
		token.T_4:  "identifier",
		token.T_6:  "number_literal",
		token.T_9:  "string_literal",
		token.T_10: "{",
		token.T_11: "}",
	},
	// Values : Value delimiter Values ∙
	{
		token.T_11: "}",
	},
	// Values : ∙
	{
		token.T_11: "}",
	},
}

var followSets = []map[token.Type]string{
	// Literal
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Manifest
	{
		token.EOF: "$",
	},
	// Namespace
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Namespaces
	{
		token.EOF: "$",
	},
	// Parameters
	{
		token.T_7: "op_define",
	},
	// Tuple
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Value
	{
		token.EOF:  "$",
		token.T_2:  "delimiter",
		token.T_4:  "identifier",
		token.T_8:  "separator",
		token.T_11: "}",
	},
	// Values
	{
		token.T_11: "}",
	},
}

/*** Errors ***/

/*
Error is returned by Parse at every point at which the parser fails to parse
a grammar production. For non-LL-1 grammars there will be an error for each
alternate attempted by the parser.

The errors are sorted in descending order of input position (index of token in
the stream of tokens).

Normally the error of interest is the one that has parsed the largest number of
tokens.
*/
type Error struct {
	// Index of token that caused the error.
	cI int

	// Grammar slot at which the error occured.
	Slot slot.Label

	// The token at which the error occurred.
	Token *token.Token

	// The line and column in the input text at which the error occurred
	Line, Column int

	// The tokens expected at the point where the error occurred
	Expected map[token.Type]string
}

func (pe *Error) String() string {
	w := new(bytes.Buffer)
	fmt.Fprintf(w, "Parse Error: %s I[%d]=%s at line %d col %d\n",
		pe.Slot, pe.cI, pe.Token, pe.Line, pe.Column)
	exp := []string{}
	for _, e := range pe.Expected {
		exp = append(exp, e)
	}
	fmt.Fprintf(w, "Expected one of: [%s]", strings.Join(exp, ","))
	return w.String()
}

func (p *parser) parseError(slot slot.Label, i int, expected map[token.Type]string) {
	pe := &Error{cI: i, Slot: slot, Token: p.lex.Tokens[i], Expected: expected}
	p.parseErrors = append(p.parseErrors, pe)
}

func (p *parser) sortParseErrors() {
	sort.Slice(p.parseErrors,
		func(i, j int) bool {
			return p.parseErrors[j].Token.Lext() < p.parseErrors[i].Token.Lext()
		})
	for _, pe := range p.parseErrors {
		pe.Line, pe.Column = p.lex.GetLineColumn(pe.Token.Lext())
	}
}
