// Code generated by gogll. DO NOT EDIT.

package symbols

import (
	"bytes"
	"fmt"
)

type Symbol interface {
	isSymbol()
	IsNonTerminal() bool
	String() string
}

func (NT) isSymbol() {}
func (T) isSymbol()  {}

// NT is the type of non-terminals symbols
type NT int

const (
	NT_Literal NT = iota
	NT_Manifest
	NT_Namespace
	NT_Namespaces
	NT_Parameters
	NT_Tuple
	NT_Value
	NT_Values
)

// T is the type of terminals symbols
type T int

const (
	T_0  T = iota // block_comment
	T_1           // boolean_literal
	T_2           // delimiter
	T_3           // expr_literal
	T_4           // identifier
	T_5           // line_comment
	T_6           // number_literal
	T_7           // op_define
	T_8           // separator
	T_9           // string_literal
	T_10          // {
	T_11          // }
)

type Symbols []Symbol

func (ss Symbols) Equal(ss1 Symbols) bool {
	if len(ss) != len(ss1) {
		return false
	}
	for i, s := range ss {
		if s.String() != ss1[i].String() {
			return false
		}
	}
	return true
}

func (ss Symbols) String() string {
	w := new(bytes.Buffer)
	for i, s := range ss {
		if i > 0 {
			fmt.Fprint(w, " ")
		}
		fmt.Fprintf(w, "%s", s)
	}
	return w.String()
}

func (ss Symbols) Strings() []string {
	strs := make([]string, len(ss))
	for i, s := range ss {
		strs[i] = s.String()
	}
	return strs
}

func (NT) IsNonTerminal() bool {
	return true
}

func (T) IsNonTerminal() bool {
	return false
}

func (nt NT) String() string {
	return ntToString[nt]
}

func (t T) String() string {
	return tToString[t]
}

// IsNT returns true iff sym is a non-terminal symbol of the grammar
func IsNT(sym string) bool {
	_, exist := stringNT[sym]
	return exist
}

// ToNT returns the NT value of sym or panics if sym is not a non-terminal of the grammar
func ToNT(sym string) NT {
	nt, exist := stringNT[sym]
	if !exist {
		panic(fmt.Sprintf("No NT: %s", sym))
	}
	return nt
}

var ntToString = []string{
	"Literal",    /* NT_Literal */
	"Manifest",   /* NT_Manifest */
	"Namespace",  /* NT_Namespace */
	"Namespaces", /* NT_Namespaces */
	"Parameters", /* NT_Parameters */
	"Tuple",      /* NT_Tuple */
	"Value",      /* NT_Value */
	"Values",     /* NT_Values */
}

var tToString = []string{
	"block_comment",   /* T_0 */
	"boolean_literal", /* T_1 */
	"delimiter",       /* T_2 */
	"expr_literal",    /* T_3 */
	"identifier",      /* T_4 */
	"line_comment",    /* T_5 */
	"number_literal",  /* T_6 */
	"op_define",       /* T_7 */
	"separator",       /* T_8 */
	"string_literal",  /* T_9 */
	"{",               /* T_10 */
	"}",               /* T_11 */
}

var stringNT = map[string]NT{
	"Literal":    NT_Literal,
	"Manifest":   NT_Manifest,
	"Namespace":  NT_Namespace,
	"Namespaces": NT_Namespaces,
	"Parameters": NT_Parameters,
	"Tuple":      NT_Tuple,
	"Value":      NT_Value,
	"Values":     NT_Values,
}
